@Library('shared-library@main') _
pipeline {
    agent any

    stages {

        stage("deploy") {
            steps {
                script{
                    def config=[namespace:"app3",yaml:"k8s/app3.yaml"]
                    deployApp(config)
              }
          }
     }
 }

    post {
        success {
            echo 'app3 deploy completato con successo'
        }
        failure {
            echo 'Errore nel deploy App3'
        }
    }
}
