pipeline {
    agent any

    stages {

        stage("deploy") {
            steps {
                sh '''
                  kubectl get namespace app3 || kubectl create namespace app3
                  kubectl -n app3 apply -f k8s/app3.yaml
                '''
            }
        }
    }

    post {
        success {
            echo 'app3 deploy completato con successo'
        }
        failure {
            echo 'Errore nel deploy App3'
        }
    }
}
